In [7]:
import requests,json
import pandas as pd

def AA_app_ranks(platform, countries, ranks, categories, granularity, device, start_date):
    r = requests.get('https://api.appannie.com/v1.3/intelligence/apps/' + platform + '/ranking?' +
                     'countries=' + countries +
                     '&categories=' + categories +
                     '&feeds=free' +
                     '&ranks=' + ranks +
                     '&granularity=' + granularity +
                     '&device=' + device +
                     '&start_date=' + start_date,
                     headers={'Authorization': 'bearer da420ceb1867f439bc7f3f64f21437749ba074a8'})
    return pd.DataFrame(r.json()['list']['free'])

def AA_publisher_ranks(platform, countries, ranks, categories, granularity, device, start_date):
    r = requests.get('https://api.appannie.com/v1.3/intelligence/apps/' + platform + '/publisher-ranking?' +
                     'countries=' + countries +
                     '&categories=' + categories +
                     '&feeds=free' +
                     '&ranks=' + ranks +
                     '&granularity=' + granularity +
                     '&device=' + device +
                     '&start_date=' + start_date,
                     headers={'Authorization': 'bearer da420ceb1867f439bc7f3f64f21437749ba074a8'})

    return pd.DataFrame(r.json()['list']['free'])# Get AA data

In [4]:
AA_ios_1000 = AA_app_ranks('ios','US','0-1000', 'Overall > Games','daily','ios','2021-01-21')

In [5]:
AA_ios_1000

     estimate  product_id  rank
0      125274  1545306176     1
1       84286  1534712015     2
2       71608  1483058899     3
3       55053  1542737365     4
4       49055  1351168404     5
5       45707  1536131108     6
6       39557  1524760095     7
7       38439   431946152     8
8       35495   512939461     9
9       35305  1523081624    10
10      34500  1540979366    11
11      34396  1533397036    12
12      34325  1514542157    13
13      32222  1287282214    14
14      30575  1538288955    15
15      29275  1515957122    16
16      26911  1502447854    17
17      25840  1518389230    18
18      25260  1538238661    19
19      24244  1195621598    20
20      23875  1534471879    21
21      22865  1530162419    22
22      22710  1443446174    23
23      21877  1539324945    24
24      21401  1519029260    25
25      21319  1522899035    26
26      20553  1344700142    27
27      19777  1330123889    28
28      19471  1528269945    29
29      19283  1499081620    30
..        ...         ...   ...
970      1395  1523500596   971
971      1393  1490571442   972
972      1391  1534137488   973
973      1390  1458014773   974
974      1387  1467148530   975
975      1387  1485713686   976
976      1386   917683741   977
977      1383   893372761   978
978      1383  1067644352   979
979      1382  1492980232   980
980      1380   561416817   981
981      1379  1523094856   982
982      1378  1473736890   983
983      1374  1215477266   984
984      1372  1525162233   985
985      1368   657459418   986
986      1365  1153461915   987
987      1365  1524323128   988
988      1361  1089225191   989
989      1359  1509453362   990
990      1359  1517461736   991
991      1359  1538448348   992
992      1356  1471527199   993
993      1354  1483602174   994
994      1354  1488306871   995
995      1353   940292587   996
996      1353  1380831764   997
997      1352   566661426   998
998      1350   996023954   999
999      1349   985158853  1000

[1000 rows x 3 columns]

In [8]:
AA_ios_publisher_1000 = AA_publisher_ranks('ios','US','0-1000', 'Overall > Games','daily','ios','2021-01-21')

In [9]:
AA_ios_publisher_1000

     estimate  publisher_id  rank
0      352324     714804730     1
1      248407    1362220666     2
2      221000    1452111779     3
3      157736    1405039362     4
4      151657    1191495496     5
5      147941    1499845738     6
6      126279     721307559     7
7       84305    1508482093     8
8       71608    1483058897     9
9       67774    1441389613    10
10      65852     497961736    11
11      65626     295913422    12
12      63595     892399717    13
13      59455    1483575279    14
14      54864    1162116447    15
15      54675     284800461    16
16      53874    1478916023    17
17      50806    1487320337    18
18      49055     957995279    19
19      48185    1466935753    20
20      40985    1190815537    21
21      39677    1225503009    22
22      38439     431946155    23
23      37662     337457683    24
24      37297    1480976125    25
25      36032     465882936    26
26      35760     471259040    27
27      35374    1275177033    28
28      32222     285005466    29
29      31879    1022434729    30
..        ...           ...   ...
970       737    1534493314   971
971       736     982108280   972
972       734     338533084   973
973       733     314395447   974
974       731    1399645502   975
975       729     505994116   976
976       726     913182073   977
977       726    1347147799   978
978       726    1448612482   979
979       726    1500739240   980
980       726    1534588023   981
981       726    1541367616   982
982       725     535176912   983
983       724    1316911966   984
984       722    1375487393   985
985       721    1175843955   986
986       721    1481048077   987
987       721    1499817708   988
988       721    1503022996   989
989       718    1032208485   990
990       716     452269707   991
991       715     436322060   992
992       715     669871978   993
993       713     730234819   994
994       713    1442760485   995
995       713    1532186210   996
996       710    1478756221   997
997       707    1548003819   998
998       704    1528286964   999
999       703     819195926  1000

[1000 rows x 3 columns]